defmodule FluentlyWeb.Endpoint do
  use Sentry.PlugCapture, scrubber: {Fluently.Sentry.Privacy, :scrub_conn, []}
  use Phoenix.Endpoint, otp_app: :fluently

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fluently_key",
    signing_salt: "rst9xFM7",
    same_site: "Lax",
    max_age: 2_592_000,
    http_only: true,
    secure: Application.compile_env(:fluently, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fluently,
    gzip: not code_reloading?,
    only: FluentlyWeb.static_paths(),
    only_matching: ["embed-"],
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fluently
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug FluentlyWeb.ClientIP
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    length: 32_768,
    body_reader: {FluentlyWeb.RequestBody, :read_body, []},
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Sentry.PlugContext,
    body_scrubber: nil,
    header_scrubber: nil,
    cookie_scrubber: nil,
    remote_address_reader: nil,
    url_scrubber: {Fluently.Sentry.Privacy, :url}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FluentlyWeb.Router
end
